# default values
dev:
  webpath:   http://skymp3.sky/skyadnin
  upload_dir:   http://skymp3.sky/siteuploads
  frontsiteurl:   http://skymp3.sky
  webmaster: 
  filename2hide: -(dev.in)
  sitename: skymp3.in

skymp3:
  webpath:   http://skymp3.in/skyadnin
  upload_dir:   http://skymp3.in/siteuploads
  webmaster: admin@skymp3.in
  frontsiteurl:   http://skymp3.in
  filename2hide: (SKYMp3.In)
  sitename: SKYMp3.In

all:
  setorder: on
  sfImageTransformPlugin:
   default_adapter: GD # GD or ImageMagick
   default_image:
     mime_type: image/png
     filename: Untitled.png
     width: 100
     height: 100
     color: '#FFFFFF'
   font_dir: /usr/share/fonts/truetype/msttcorefonts
   mime_type:
     auto_detect: true
     library: gd_mime_type #  gd_mime_type (GD), Fileinfo (PECL), MIME_Type (PEAR)
  