rendering: ~
web_debug: ~
security:  ~

# generally, you will want to insert your own filters here
#remember:                 # Filters need a unique name
#  class: rememberFilter
#  param:
#    cookie_name: skyitech.skymp3

cache:     ~
common:    ~
flash:     ~
execution: ~
