default_routing:
  categoryList:
    url:   categorylist/:parent/:fname/:sort/:page.
    param: { module: category, action: list, page: 1, sort: default, fname: mp3_ringtones_wallpaper_games_themes }
  
  filesList:
    url:   filelist/:parent/:fname/:sort/:page.
    param: { module: files, action: list, fname: mp3_ringtones_wallpaper_games_themes, sort: new2old, page: 1 }
  
  filesShow:
    url:   fileDownload/:id/:name.html
    param: { module: files, action: show }
  
  lastAddedFiles:
    url:   newitems/:page.html
    param: { module: files, action: lastadded, page: 1 }
  
  featured:
    url:   featured/:page.html
    param: { module: files, action: featured, page: 1 }
  
  topFiles:
    url:   /topdownload/:type.html
    param: { module: files, action: top }
  
  latestUpdates:
    url:   latest_updates/:page.html
    param: { module: info, action: latestupdates, page: 1 }
  
  more:
    url:   more.html
    param: { module: info, action: more }

  homepage:
    url:   /
    param: { module: default, action: index }
  
  default_symfony:
    url:   /skyitech/:action/*
    param: { module: default }
  
  default_index:
    url:   /:module
    param: { action: index }
  
  default:
    url:   /:module/:action/*

  