default:
  http_metas:
    content-type: text/html

  metas:
    title:        SKYMp3.In &raquo; Development By SKYiTech.com
    robots:       index, follow
    language:     en

  stylesheets:    []

  javascripts:    []

  has_layout:     on
  layout:         layout
