<?
$langchars=array(
'English'=>'a-zA-Z',
'Russian'=>'а-яА-Я');

$GEOIP_COUNTRY_CODES=array(
'','US CA DE GB IT JP EU AT BE CH DK ES FI FR IE LU PT SE',
'AP','EU','AD','AE','AF','AG','AI','AL','AM','AN','AO','AQ',
'AR','AS','AT','AU','AW','AZ','BA','BB','BD','BE','BF','BG','BH',
'BI','BJ','BM','BN','BO','BR','BS','BT','BV','BW','BY','BZ','CA',
'CC','CD','CF','CG','CH','CI','CK','CL','CM','CN','CO','CR','CU',
'CV','CX','CY','CZ','DE','DJ','DK','DM','DO','DZ','EC','EE','EG',
'EH','ER','ES','ET','FI','FJ','FK','FM','FO','FR','FX','GA','GB',
'GD','GE','GF','GH','GI','GL','GM','GN','GP','GQ','GR','GS','GT',
'GU','GW','GY','HK','HM','HN','HR','HT','HU','ID','IE','IL','IN',
'IO','IQ','IR','IS','IT','JM','JO','JP','KE','KG','KH','KI','KM',
'KN','KP','KR','KW','KY','KZ','LA','LB','LC','LI','LK','LR','LS',
'LT','LU','LV','LY','MA','MC','MD','MG','MH','MK','ML','MM','MN',
'MO','MP','MQ','MR','MS','MT','MU','MV','MW','MX','MY','MZ','NA',
'NC','NE','NF','NG','NI','NL','NO','NP','NR','NU','NZ','OM','PA',
'PE','PF','PG','PH','PK','PL','PM','PN','PR','PS','PT','PW','PY',
'QA','RE','RO','RU','RW','SA','SB','SC','SD','SE','SG','SH','SI',
'SJ','SK','SL','SM','SN','SO','SR','ST','SV','SY','SZ','TC','TD',
'TF','TG','TH','TJ','TK','TM','TN','TO','TP','TR','TT','TV','TW',
'TZ','UA','UG','UM','US','UY','UZ','VA','VC','VE','VG','VI','VN',
'VU','WF','WS','YE','YT','YU','ZA','ZM','ZR','ZW','A1','A2','O1'
);

$GEOIP_COUNTRY_NAMES=array(
'','All Good Countries',
'Asia/Pacific Region','Europe','Andorra','United Arab Emirates',
'Afghanistan','Antigua and Barbuda','Anguilla','Albania','Armenia',
'Netherlands Antilles','Angola','Antarctica','Argentina','American Samoa',
'Austria','Australia','Aruba','Azerbaijan','Bosnia and Herzegovina',
'Barbados','Bangladesh','Belgium','Burkina Faso','Bulgaria','Bahrain',
'Burundi','Benin','Bermuda','Brunei Darussalam','Bolivia','Brazil',
'Bahamas','Bhutan','Bouvet Island','Botswana','Belarus','Belize',
'Canada','Cocos (Keeling) Islands','Congo',
'Central African Republic','Congo','Switzerland','Cote DIvoire','Cook Islands',
'Chile','Cameroon','China','Colombia','Costa Rica','Cuba','Cape Verde',
'Christmas Island','Cyprus','Czech Republic','Germany','Djibouti',
'Denmark','Dominica','Dominican Republic','Algeria','Ecuador','Estonia',
'Egypt','Western Sahara','Eritrea','Spain','Ethiopia','Finland','Fiji',
'Falkland Islands (Malvinas)','Micronesia, Federated States of','Faroe Islands',
'France','France, Metropolitan','Gabon','United Kingdom',
'Grenada','Georgia','French Guiana','Ghana','Gibraltar','Greenland',
'Gambia','Guinea','Guadeloupe','Equatorial Guinea','Greece',
'S. Georgia & Sandwich Islands','Guatemala','Guam','Guinea-Bissau',
'Guyana','Hong Kong','Heard Island and McDonald Islands','Honduras',
'Croatia','Haiti','Hungary','Indonesia','Ireland','Israel','India',
'British Indian Ocean Territory','Iraq','Iran, Islamic Republic of',
'Iceland','Italy','Jamaica','Jordan','Japan','Kenya','Kyrgyzstan',
'Cambodia','Kiribati','Comoros','Saint Kitts and Nevis',
'Korea, Democratic Peoples Rep','Korea, Republic of','Kuwait','Cayman Islands',
'Kazakstan','Lao Peoples Democratic Republic','Lebanon','Saint Lucia',
'Liechtenstein','Sri Lanka','Liberia','Lesotho','Lithuania','Luxembourg',
'Latvia','Libyan Arab Jamahiriya','Morocco','Monaco','Moldova, Republic of',
'Madagascar','Marshall Islands','Macedonia',
'Mali','Myanmar','Mongolia','Macau','Northern Mariana Islands',
'Martinique','Mauritania','Montserrat','Malta','Mauritius','Maldives',
'Malawi','Mexico','Malaysia','Mozambique','Namibia','New Caledonia',
'Niger','Norfolk Island','Nigeria','Nicaragua','Netherlands','Norway',
'Nepal','Nauru','Niue','New Zealand','Oman','Panama','Peru','French Polynesia',
'Papua New Guinea','Philippines','Pakistan','Poland','Saint Pierre and Miquelon',
'Pitcairn','Puerto Rico','Palestinian Territory, Occupied',
'Portugal','Palau','Paraguay','Qatar','Reunion','Romania',
'Russian Federation','Rwanda','Saudi Arabia','Solomon Islands',
'Seychelles','Sudan','Sweden','Singapore','Saint Helena','Slovenia',
'Svalbard and Jan Mayen','Slovakia','Sierra Leone','San Marino','Senegal',
'Somalia','Suriname','Sao Tome and Principe','El Salvador','Syrian Arab Republic',
'Swaziland','Turks and Caicos Islands','Chad','French Southern Territories',
'Togo','Thailand','Tajikistan','Tokelau','Turkmenistan',
'Tunisia','Tonga','East Timor','Turkey','Trinidad and Tobago','Tuvalu',
'Taiwan','Tanzania, United Republic of','Ukraine',
'Uganda','United States Minor Outlying Islands','United States','Uruguay',
'Uzbekistan','Holy See (Vatican City State)','Saint Vincent and the Grenadines',
'Venezuela','Virgin Islands, British','Virgin Islands, U.S.',
'Vietnam','Vanuatu','Wallis and Futuna','Samoa','Yemen','Mayotte',
'Yugoslavia','South Africa','Zambia','Zaire','Zimbabwe',
'Anonymous Proxy','Satellite Provider','Other'
);

$intlangs=array('English','Russian','Spanish','Chinese Simple');

$TXT['English']=array(
'Submit New Site'=>'Submit New Site',
'URL of your page'=>'URL of your page',
'Fake URL'=>'Fake URL',
'Banner URL'=>'Banner URL',
'Link Back URL'=>'Link Back URL',
'where you will place our link'=>'where you will place our link',
'Category'=>'Category',
'Site type'=>'Site type',
'Site title'=>'Site title',
'Site description'=>'Site description',
'Your Email'=>'Your Email',
'Your ICQ #'=>'Your ICQ #',
'Username'=>'Username',
'Password'=>'Password',
'Re-type your password'=>'Re-type your password',
'Add Site'=>'Add Site',
'Edit Account / Check Stats'=>'Edit Account / Check Stats',
'Log In'=>'Log In',
'Forgot Password'=>'Forgot Password',
'Main page'=>'Main page',
'Download'=>'Download',
'Stats for current period'=>'Stats for current period',
'Traffic Summary'=>'Traffic Summary',
'Visits'=>'Visits',
'Out'=>'Out',
'Account Submitted to'=>'Account Submitted to',
'Your account has been added to'=>'Your account has been added to',
'Account will be listed after review'=>'Account will be listed after review',
'You may start sending hits immediately'=>'You may start sending visitors immediately',
'Place this link at your page'=>'Place this link at your page',
'All hits from domain'=>'All visitors from domain',
'will be counted as your hits'=>'will be counted as your visitors',
'Edit account and view stats'=>'Edit account and view stats',
'Thanks for signing up to'=>'Thanks for signing up to',
'You may start sending and recieving hits immediately'=>'You may start sending and recieving visitors immediately',
'Email me for any questions'=>'Email me for any questions',
'or icq me at'=>'or icq me at'
);

$TXT['Russian']=array(
'Submit New Site'=>'Добавить ваш сайт',
'URL of your page'=>'URL вашей страницы',
'Fake URL'=>'Ложный URL',
'Banner URL'=>'URL баннера',
'Link Back URL'=>'URL обратной ссылки',
'where you will place our link'=>'где вы разместите нашу ссылку',
'Category'=>'Раздел',
'Site type'=>'Тип сайта',
'Site title'=>'Название сайта',
'Site description'=>'Описание сайта',
'Your Email'=>'Ваш Email',
'Your ICQ #'=>'Ваш ICQ #',
'Username'=>'Имя пользователя',
'Password'=>'Пароль',
'Re-type your password'=>'Повторите пароль',
'Add Site'=>'Добавить сайт',
'Edit Account / Check Stats'=>'Изменить описание / Проверить статистику',
'Log In'=>'Войти',
'Forgot Password'=>'Забыл пароль',
'Main page'=>'Главная',
'Download'=>'Скачать',
'Stats for current period'=>'Статистика за период',
'Traffic Summary'=>'Суммарный трафик',
'Visits'=>'Посетителей',
'Account Submitted to'=>'Сайт добавлен в',
'Out'=>'Кликов',
'Your account has been added to'=>'Ваш сайт добавлен в',
'Account will be listed after review'=>'Сайт появится в списке после одобрения',
'You may start sending hits immediately'=>'Вы можете начинать отправку трафика немедленно',
'Place this link at your page'=>'Разместите эту ссылку на вашей странице',
'All hits from domain'=>'Все переходы с домена',
'will be counted as your hits'=>'будут засчитаны вашему сайту',
'Edit account and view stats'=>'Редактирование данных и просмотр статистики',
'Thanks for signing up to'=>'Спасибо за регистрацию в',
'You may start sending and recieving hits immediately'=>'Вы можете начинать отправлять и получать посетителей немедленно',
'Email me for any questions'=>'С вопросами обращайтесь',
'or icq me at'=>'или icq'
);

$TXT['Spanish']=array(
'Submit New Site'=>'Inscribir su web',
'URL of your page'=>'Direccion URL de su web',
'Fake URL'=>'URL Enmascarada',
'Banner URL'=>'Banner URL',
'Link Back URL'=>'Direccion URL del link reciproco',
'where you will place our link'=>'donde incluira nuestro codigo',
'Category'=>'Categoria',
'Site type'=>'Tipo de Sitio',
'Site title'=>'Titulo de su web',
'Site description'=>'Descripcion de su sitio',
'Your Email'=>'Su Email',
'Your ICQ #'=>'Su ICQ/Messenger',
'Username'=>'Cuenta',
'Password'=>'Password',
'Re-type your password'=>'Reingresar password',
'Add Site'=>'Inscribir su web',
'Edit Account / Check Stats'=>'Editar su cuenta / Acceso a estaditicas',
'Log In'=>'Acceder',
'Forgot Password'=>'Forgot Password',
'Main page'=>'Pagina Principal',
'Download'=>'Download',
'Stats for current period'=>'Estadisticas para periodo actual',
'Traffic Summary'=>'Resumen de trafico',
'Visits'=>'Visita',
'Out'=>'Salida',
'Account Submitted to'=>'Confirmacion de',
'Your account has been added to'=>'Ha sido agregado en',
'Account will be listed after review'=>'Su cuenta sera aprobada luego de la revision',
'You may start sending hits immediately'=>'Debe enviar al menos una visita desde su web para validar su cuenta ',
'Place this link at your page'=>'Debe poner y mantener este enlace en su web',
'All hits from domain'=>'Todos los hits del dominio',
'will be counted as your hits'=>'se contabilizar como sus hits',
'Edit account and view stats'=>'Editar su cuenta y ver estadisticas',
'Thanks for signing up to'=>'Gracias por inscribirse en ',
'You may start sending and recieving hits immediately'=>'Ya puede comenzar a enviar y recibir visitas',
'Email me for any questions'=>'Contactenos ',
'or icq me at'=>'o por messenger',
);

$TXT['Chinese Simple']=array(
'Submit New Site'=>'МбЅ»ДъµДНшХѕ',
'URL of your page'=>'ДъµДНшХѕµШЦ·',
'Fake URL'=>'Fake URL',
'Banner URL'=>'Banner №гёжµШЦ·',
'Link Back URL'=>'»ШБґµШЦ·',
'where you will place our link'=>'Дъ»бФЪДъµДДДёцµШЦ·јУЙПОТГЗµДНшХѕµШЦ·',
'Category'=>'ДїВј',
'Site type'=>'НшХѕАаРН',
'Site title'=>'НшХѕ±кМв',
'Site description'=>'НшХѕГиКц',
'Your Email'=>'ДъµДµзЧУУКјю',
'Your ICQ #'=>'ДъµДQQєЕ #',
'Username'=>'УГ»§Гы',
'Password'=>'ГЬВл',
'Re-type your password'=>'ЦШКдГЬВл',
'Add Site'=>'ФцјУНшХѕБ¬ЅУ',
'Edit Account / Check Stats'=>'ХК»§±ај­ / ЧґМ¬јмІй',
'Log In'=>'ЧўІб',
'Forgot Password'=>'НьјЗГЬВл',
'Main page'=>'ЦчТі',
'Download'=>'ПВФШ',
'Stats for current period'=>'µ±З°ЧґМ¬',
'Traffic Summary'=>'ЧЬБчБї',
'Visits'=>'·ГОКХЯ',
'Out'=>'Out',
'Account Submitted to'=>'ХК»§МбЅ»µЅ',
'Your account has been added to'=>'ДъµДХК»§ТСѕ­±»јУµЅБЛ',
'Account will be listed after review'=>'НЁ№эЙуєЛєуЈ¬ДъµДХК»§Ѕ«±»БРіц',
'You may start sending hits immediately'=>'ДъїЙТФїЄКјЕЬБчБїБЛ',
'Place this link at your page'=>'Зл°СХвёцБ¬ЅУ·ЕµЅДъµДНшТіЙП',
'All hits from domain'=>'ґУХвёцУтГыАґµДµг»чКэ',
'will be counted as your hits'=>'Ѕ«јЗВјіЙОЄДъµДµг»чКэ',
'Edit account and view stats'=>'±ај­ХК»§ІўІйїґЧґМ¬',
'Thanks for signing up to'=>'Р»Р»ДъЧўІбіЙОЄ',
'You may start sending and recieving hits immediately'=>'ДъїЙТФїЄКјЛНєНКЬµЅµг»чБЛ',
'Email me for any questions'=>'УРОКМвЗлEmailёшОТ',
'or icq me at'=>'»тХЯєфОТµДQQ'
);
?>