<?php
print '<!DOCTYPE html PUBLIC "-//WAPFORUM//DTD XHTML Mobile 1.0//EN" "http://www.wapforum.org/DTD/xhtml-mobile10.dtd"><html xmlns="http://www.w3.org/1999/xhtml"> <head><meta http-equiv="content-language" content="en, bn"> <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0"><link href="m.css?v=1.5" rel="stylesheet" type="text/css"> </head> <body>';

print '<div class="i"><font size="">MostBd.Com</font></div>';

print '<div class="cv cx dz"><div><a href="">Bangla News</a></div>Something went here 1</div><div class="cv cx dz"><div><a href="">Top News</a></div>Something went here 2</div><div class="cv cx dz"><div><a href="">Latest News</a></div>Something went here 3</div><div class="cv cx dz"><div><a href="">Hot News</a></div>Something went here 4</div><div class="cv cx dz"><div><a href="">Best News</a></div>Something went here 5</div>';

print '<div class="cv cx dz"><div><a href="">Bangla News</a></div>Something went here 1</div><div class="cv cx dz"><div><a href="">Top News</a></div>Something went here 2</div><div class="cv cx dz"><div><a href="">Latest News</a></div>Something went here 3</div><div class="cv cx dz"><div><a href="">Hot News</a></div>Something went here 4</div><div class="cv cx dz"><div><a href="">Best News</a></div>Something went here 5</div>';
print '<div class="cv cx dz"><div><a href="">Bangla News</a></div>Something went here 1</div><div class="cv cx dz"><div><a href="">Top News</a></div>Something went here 2</div><div class="cv cx dz"><div><a href="">Latest News</a></div>Something went here 3</div><div class="cv cx dz"><div><a href="">Hot News</a></div>Something went here 4</div><div class="cv cx dz"><div><a href="">Best News</a></div>Something went here 5</div>';
print '<div class="cv cx dz"><div><a href="">Bangla News</a></div>Something went here 1</div><div class="cv cx dz"><div><a href="">Top News</a></div>Something went here 2</div><div class="cv cx dz"><div><a href="">Latest News</a></div>Something went here 3</div><div class="cv cx dz"><div><a href="">Hot News</a></div>Something went here 4</div><div class="cv cx dz"><div><a href="">Best News</a></div>Something went here 5</div>';




print '<footer class="footer"> <div id="search"> <form method="get" action="" class="search-form"> <input type="text" name="q" class="inp-text"/> <input type="submit" value="Search" class="inp-button"/> </form> </div><ul class="col-full category-list" id="category"><ul class="col-half"><li class="link"><a href="">Bangla Sms</a></li><li class="link"><a href="">বাংলা এসএমএস</a></li></ul><ul class="col-half"><li class="link"><a href="">Hindi sms</a></li><li class="link"><a href="">English Sms</a></li></ul><div class="clear"></div><ul class="col-half"><li class="link"><a href="">ইসলামের কথা</a></li><li class="link"><a href="">প্রাত্যহিক আয়োজন</a></li><li class="link"><a href="">বিনোদন ডেস্ক</a></li><li class="link"><a href="">খেলাধুলার খবর</a></li><li class="link"><a href="">অন্যরকম খবর</a></li><li class="link"><a href="">দেশ-বিদেশের খবর</a></li><li class="link"><a href="">দৈনন্দিন জীবন</a></li><li class="link"><a href="">টিপস এবং ট্রিক</a></li><li class="link"><a href="">বিজ্ঞান ও প্রযুক্তি</a></li><li class="link"><a href="">রিভিউ সমগ্র</a></li></ul><ul class="col-half"><li class="link"><a href="">গল্প সমগ্র</a></li><li class="link"><a href="">কবিতা সমগ্র</a></li><li class="link"><a href="">অপরেটর নিউজ</a></li><li class="link"><a href="">বিশেষ আয়োজন</a></li><li class="link"><a href="">গানের কথা</a></li><li class="link"><a href="">অন্যান্য ও মজা</a></li><li class="link"><a href="">বাংলা কৌতুক</a></li><li class="link"><a href="">জানা ও অজানা</a></li><li class="link"><a href="">পড়াশোনা</a></li><li class="link"><a href="">চাকুরির বিজ্ঞপ্তি</a></li></ul><div class="clear"></div></ul><ul class="footer-links"> <li><a href="">Help</a></li><li><a href="">About</a></li><li><a href="">Terms</a></li> <li id="right"><a href="#top">Goto Top</a></li></ul> <div class="clear"></div> <div class="copyright">© 2010-2016 MostBD.Com</div> </footer> </body> </html>';
?>